/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TestReportRouteImport } from './routes/test-report'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingLookupRouteImport } from './routes/booking-lookup'
import { Route as AdminPreviewRouteImport } from './routes/admin-preview'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as BookingReferenceRouteImport } from './routes/booking.$reference'
import { Route as BookSlugRouteImport } from './routes/book.$slug'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TestReportRoute = TestReportRouteImport.update({
  id: '/test-report',
  path: '/test-report',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingLookupRoute = BookingLookupRouteImport.update({
  id: '/booking-lookup',
  path: '/booking-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/admin-preview',
  path: '/admin-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const BookingReferenceRoute = BookingReferenceRouteImport.update({
  id: '/booking/$reference',
  path: '/booking/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-preview': typeof AdminPreviewRoute
  '/booking-lookup': typeof BookingLookupRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/test-report': typeof TestReportRoute
  '/tours': typeof ToursRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-preview': typeof AdminPreviewRoute
  '/booking-lookup': typeof BookingLookupRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/test-report': typeof TestReportRoute
  '/tours': typeof ToursRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-preview': typeof AdminPreviewRoute
  '/booking-lookup': typeof BookingLookupRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/test-report': typeof TestReportRoute
  '/tours': typeof ToursRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-preview'
    | '/booking-lookup'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/test-report'
    | '/tours'
    | '/transfers'
    | '/unsubscribe'
    | '/book/$slug'
    | '/booking/$reference'
    | '/tours/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-preview'
    | '/booking-lookup'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/test-report'
    | '/tours'
    | '/transfers'
    | '/unsubscribe'
    | '/book/$slug'
    | '/booking/$reference'
    | '/tours/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-preview'
    | '/booking-lookup'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/test-report'
    | '/tours'
    | '/transfers'
    | '/unsubscribe'
    | '/book/$slug'
    | '/booking/$reference'
    | '/tours/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  BookingLookupRoute: typeof BookingLookupRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  TestReportRoute: typeof TestReportRoute
  ToursRoute: typeof ToursRouteWithChildren
  TransfersRoute: typeof TransfersRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingReferenceRoute: typeof BookingReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-report': {
      id: '/test-report'
      path: '/test-report'
      fullPath: '/test-report'
      preLoaderRoute: typeof TestReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-lookup': {
      id: '/booking-lookup'
      path: '/booking-lookup'
      fullPath: '/booking-lookup'
      preLoaderRoute: typeof BookingLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-preview': {
      id: '/admin-preview'
      path: '/admin-preview'
      fullPath: '/admin-preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/booking/$reference': {
      id: '/booking/$reference'
      path: '/booking/$reference'
      fullPath: '/booking/$reference'
      preLoaderRoute: typeof BookingReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  BookingLookupRoute: BookingLookupRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  TestReportRoute: TestReportRoute,
  ToursRoute: ToursRouteWithChildren,
  TransfersRoute: TransfersRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BookSlugRoute: BookSlugRoute,
  BookingReferenceRoute: BookingReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
